rule all:
    input:
        "results/step_three.txt"

rule step_two:
    output:
        "data/step_two.txt",
    conda:
        "envs/step_two.yaml"
    shell:
        "plink2 --version > {output}"

rule step_three:
    input:
        "data/step_two.txt",
    output:
        "results/step_three.txt",
    script:
        "scripts/step_three.py"